components:
  heat:
    containers: false
    logs:
    - /var/log/heat/
  contrail-haproxy:
    containers: false
    logs:
    - /var/log/haproxy.log
  neutron:
    containers: false
    logs:
    - /var/log/neutron/
  contrail-agent:
    containers: true
    logs:
    - /var/log/contrail/
  contrail-controller:
    containers: true
    logs:
    - /var/log/contrail/
  contrail-analyticsdb:
    containers: true
    logs:
    - /var/log/contrail/
  contrail-analytics:
    containers: true
    logs:
    - /var/log/contrail/
  appformix:
    containers: true
    logs:
    - /var/log/appformix/
filter_strings:
  hostname_string: 'juju'
  domain_string: 'maas'
